#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/a00c8c40-e324-4c7f-944e-6242813a293e 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudTemperatureSensor temp;
  CloudRelativeHumidity humi;
  bool led;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <DHT.h>

int ledpin = 2;
int dhtpin = 15;

# define DHTTYPE DHT11
DHT dht(dhtpin, DHTTYPE);

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 
  
  dht.begin();
  pinMode(ledpin, OUTPUT);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  DHT_read();
  // Your code here 
}

/*
  Since Led is READ_WRITE variable, onLedChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLedChange()  {
  // Add your code here to act upon Led change
  if (led) {
    digitalWrite(ledpin, HIGH);  // Turn the LED on
    Serial.println("LED is ON");
  } else {
    digitalWrite(ledpin, LOW);   // Turn the LED off
    Serial.println("LED is OFF");
  }
}

void DHT_read()
{
  float h = dht.readHumidity();
  float t = dht.readTemperature();

  temp = t;
  humi = h;
  
  //Serial.println("Temperature: ", t);
  //Serial.println("Humidity: ", h);
  delay(1000);
}
